openapi: 3.1.0
info:
  title: Структура сообщения `async-job.job-posting-evaluate-result`
  version: 1.0.0
paths: {}
components:
  schemas:
    Message:
      type: object
      properties:
        headers:
          allOf:
            - $ref: '../common-orchestration-message.yaml#/components/schemas/MessageHeaders'
            - $ref: '#/components/schemas/MessageHeaders'
        payload:
          allOf:
            - $ref: '../common-async-job-result-message.yaml#/components/schemas/MessagePayload'
            - $ref: '#/components/schemas/MessagePayload'
      required:
        - headers
        - payload
  MessageHeaders:
    type: object
    properties:
      type:
        type: string
        enum:
          - async-job.job-posting-evaluate-result
        description: Тип сообщения
      required:
        - type
  MessagePayload:
    type: object
    properties:
      jobPostingUuid:
        type: string
        format: uuid
        description: UUID оцененной вакансии
      evaluationStatus:
        $ref: '../../services/job-postings-crud/openapi.yaml#/components/schemas/EvaluationStatus'
      relevance:
        type: number
        format: double
        description: Релевантность вакансии
        example: 0.8040228486061096
      required:
        - jobPostingUuid
        - evaluationStatus
        - relevance