openapi: 3.1.0
info:
  title: Сервис автоматического оценивания вакансий
  version: 1.3.0
servers:
  - url: http://job-postings-evaluator:8080/
  - url: http://localhost:8082/
tags:
  - name: evaluate
    description: Контроллер оценивания вакансий
paths:
  /evaluate/sync/list:
    post:
      description: Синхронный запуск оценки
      tags:
        - evaluate
      requestBody: 
        description: Список UUID вакансий, котрые надо оценить
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/UuidsList'
      responses: 
        '200': 
          description: Успешно запущена оценка
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/SyncEvaluationResult'
        '400':
          description: Некорректный запрос
        '404':
          description: Не найдены вакансии с таким uuid
        '500':
          $ref: '#/components/responses/UncaughtException'

  /evaluate/sync/{jobPostingUuid}:
    post:
      description: Синхронный запуск оценки одной вакансии
      tags:
        - evaluate
      parameters: 
        - $ref: '#/components/parameters/RequiredEntityUuid'
      responses: 
        '200': 
          description: Успешно запущена оценка
          content: 
            application/json: 
              schema: 
                type: object
                properties: 
                  status:
                    $ref: '#/components/schemas/EvaluationStatus'
        '400':
          description: Некорректный запрос
        '404':
          description: Не найдены вакансии с таким uuid
        '500':
          $ref: '#/components/responses/UncaughtException'
          

  /evaluate/async/list:
    post:
      description: Асинхронный запуск оценки
      tags:
        - evaluate
      requestBody: 
        description: Список UUID вакансий, котрые надо оценить
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/UuidsList'
      responses: 
        '200': 
          description: Успешно запущена оценка
        '400':
          description: Некорректный запрос
        '500':
          $ref: '#/components/responses/UncaughtException'
          

  /evaluate/async/{jobPostingUuid}:
    post:
      description: Асинхронный запуск оценки одной вакансии
      tags:
        - evaluate
      parameters: 
        - $ref: '#/components/parameters/RequiredEntityUuid'
      responses: 
        '200': 
          description: Успешно запущена оценка
        '400':
          description: Некорректный запрос
        '500':
          $ref: '#/components/responses/UncaughtException'
  /evaluate/async/batch:
    post:
      description: Запуск пакетной обработки
      tags:
        - evaluate
      requestBody: 
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/BatchAsyncProcessingParameters'
      responses: 
        '200': 
          description: Успешно запущена оценка
        '500':
          $ref: '#/components/responses/UncaughtException'
components:
  schemas:
    BatchAsyncProcessingParameters:
      description: Параметры пакетной обработки
      type: object
      properties: 
        size:
          type: number
          minimum: 1
      required: 
        - size
    SyncEvaluationResult:
      type: array
      items:
        $ref: '#/components/schemas/SyncEvaluationResultItem'
    SyncEvaluationResultItem:
      type: object
      properties: 
        uuid:
          type: string
          format: uuid
        status:
          $ref: '#/components/schemas/EvaluationStatus'
      required: 
        - uuid
        - status
    EvaluationStatus:
      type: string
      enum:
        - NEW
        - PENDING
        - IRRELEVANT
        - RELEVANT
    UuidsList:
      description: Список любых UUID v4
      type: object
      properties: 
        list:
          type: array
          items: 
            type: string
            format: uuid
      required: 
        - list
  parameters:
    RequiredEntityUuid:
      name: jobPostingUuid
      in: path
      schema:
        type: string
        format: uuid
      required: true
    Size:
      name: size
      in: query
      description: "Количество записей для возврата"
      schema:
        type: integer
        default: 20
      required: false
    Page:
      name: page
      in: query
      description: "Номер страницы"
      schema:
        type: integer
        default: 1
      required: false
  responses:
    UncaughtException:
      description: Неизвестная ошибка
      content:
        text/plain:
          schema:
            type: string
          example: |
            2020-12-04 15:03:12.926 ERROR 80850 --- [         task-1] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.yawintutor.TestService.print(int)
                java.lang.ArithmeticException: / by zero
                  at com.yawintutor.TestService.print(TestService.java:15) ~[classes/:na]
                  at com.yawintutor.TestService$$FastClassBySpringCGLIB$$284b10a4.invoke(<generated>) ~[classes/:na]
                  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.1.jar:5.3.1]
