openapi: 3.0.4
info:
  title: Job posting scraping agent - sentence transformer
  version: 1.0.0
servers:
  - url: http://localhost:8000/sentence-transformer
  - url: http://sentence-transformer:8000/sentence-transformer
paths:
  /health:
    get:
      description: Health check
      responses:
        '200':
          description: Ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LivenessProbe'
        '503':
          description: Not available
          content:
            text/plain:
               example: "division by zero"
  /text/vectorize:
    post:
      description: Вычислить векторное представление текста
      requestBody:
        description: Текст, который надо векторизовать
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextCorpus'
      responses:
        '200':
          description: Вектор вычислен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vector'
        '413':
          description: Длина текста превышает доступный контекст модели
        '500':
          description: Неизвестная ошибка
          content:
            text/plain:
               example: "division by zero"
  /vectors/cosine-similarity:
    post:
      description: Вычислить косинусное сходство двух векторов
      requestBody:
        description: Два вектора
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VectorsPair'
      responses:
        '200':
          description: Результат вычисления в процентах
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CosineSimilarity'
        '500':
          description: Неизвестная ошибка
          content:
            text/plain:
               example: "division by zero"
  
components:
  schemas:
    LivenessProbe:
      type: object
      properties:
        status:
          type: string
          enum:
            - READY
    Vector:
      type: array
      items:
        type: number
    TextCorpus:
      type: object
      properties:
        text:
          type: string
    VectorsPair:
      type: object
      properties:
        left:
          $ref: '#/components/schemas/Vector'
        right:
          $ref: '#/components/schemas/Vector'
    CosineSimilarity:
      type: object
      properties:
        similarity:
          type: number
          example: 0.7689