CREATE TYPE crawler_settings.css_query_selector_type AS ENUM (
    'JOB_POSTING_LIST_CARDS',
    'JOB_POSTING_LIST_CARD_TITLE',
    'JOB_POSTING_LIST_CARD_CONTENT_LINK',
    'JOB_POSTING_LIST_PAGES_LINKS',
    'JOB_POSTING_CARD_CONTENT'
);