openapi: 3.1.0
info:
  title: Управление настройками сканера сайтов
  version: 1.0.0
servers:
  - url: http://crawler-settings-manager:8080/
paths:
  /query-selector/list:
    get:
      description: Получение списка CSS-селекторов
      responses: 
        '200':
          description: Список установленных селекторов
          content: 
            application/json: 
              schema: 
                $ref: '#/components/schemas/CssQuerySelectorsList'
  /query-selector/{selectorType}:
    get:
      description: Получение селектора
      parameters: 
        - $ref: '#/components/parameters/SelectorType'
      responses: 
        '200':
          description: CSS-селектор
          content: 
            text/plain: 
    post:
      description: Установка селектора
      parameters: 
        - $ref: '#/components/parameters/SelectorType'
      requestBody: 
        content: 
          text/plain: 
      responses: 
        '200':
          description: CSS-селектор установлен
    delete:
      description: Очистка селектора
      parameters: 
        - $ref: '#/components/parameters/SelectorType'
      responses: 
        '200':
          description: CSS-селектор удален

components:
  schemas:
    CssQuerySelectorsList:
      type: object
      properties: 
        list:
          type: array
          items:
            $ref: '#/components/schemas/CssQuerySelectorsListItem'
    CssQuerySelectorsListItem:
      type: object
      properties: 
        selector:
          type: string
        type:
          $ref: '#/components/schemas/CssQuerySelectorType'
    CssQuerySelectorType:
      type: string
      enum:
        - JOB_POSTING_LIST_CARDS
        - JOB_POSTING_LIST_CARD_TITLE
        - JOB_POSTING_LIST_CARD_CONTENT_LINK
        - JOB_POSTING_LIST_PAGES_LINKS
        - JOB_POSTING_CARD_CONTENT
  parameters:
    SelectorType:
      name: selectorType
      in: path
      schema:
        $ref: '#/components/schemas/CssQuerySelectorType'
      required: true
